MobileSurveillanceWebApplication/Models/ViewModel/ReportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MobileSurveillanceWebApplication.Models.ViewModel
{
    public class ReportViewModel
    {
        public String TakenDate { get; set; }
        public double Distance { get; set; }
        public double TotalDistance { get; set; }
        public double Velocity { get; set; }
        public String Marker { get; set; }

        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public String Address { get; set; }

        public String TimeInterval { get; set; }

        public String TotalTime { get; set; }

        public int LocationNumber { get; set; }
    }
}

MobileSurveillanceWebApplication/Controllers/TrajectoryController.cs
using MobileSurveillanceWebApplication.Models.ApiModel;
using MobileSurveillanceWebApplication.Models.DatabaseModel;
using MobileSurveillanceWebApplication.Models.ViewModel;
using MobileSurveillanceWebApplication.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;


namespace MobileSurveillanceWebApplication.Controllers
{
    public class TrajectoryController : Controller
    {
        private const String USER_DATA_FOLDER = "/UserData/";
        //
        // GET: /Trajectory/
        private readonly MobileSurveillanceContext context = new MobileSurveillanceContext();
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult ViewDetail(string trajectoryId)
        {
            var trajectory = this.context.Trajectories.Where(x => x.Id.Equals(trajectoryId)).SingleOrDefault();
            var listLocation = trajectory.Locations.Where(x => x.IsActive).OrderBy(x => x.CreatedDate).ToList();
            var model = new TrajectoryViewModel();
            model.Id = trajectory.Id;
            model.TrajectoryName = trajectory.TrajectoryName;
            model.Status = trajectory.Status;
            model.CreateDate = trajectory.CreatedDate.ToString("dd/MM/yyyy HH:mm:ss tt");
            model.Description = trajectory.Description;
            model.LastUpdate = trajectory.LastUpdated.ToString("dd/MM/yyyy HH:mm:ss tt");
            model.TotalLocation = listLocation.Count;
            model.Author = trajectory.Account.Fullname;
            if (listLocation.Count > 0)
            {
                model.TotalTime = SupportUtility.TotalTime(listLocation.First().CreatedDate, listLocation.Last().CreatedDate);
            }
            else
            {
                model.TotalTime = "";
            }

            return View(model);
        }


        //[Authorize]
        //public ActionResult Delete(string trajectoryId)
        //{
        //    var trajectory = this.context.Trajectories.Where(x => x.Id.Equals(trajectoryId)).SingleOrDefault();
        //    this.context.Trajectories.Remove(trajectory);
        //    this.context.SaveChanges();
        //    return RedirectToAction("ListTrajectory");
        //}

        [Authorize]
        public JsonResult Delete(string trajectoryId)
        {
            var trajectory = this.context.Trajectories.Where(x => x.Id.Equals(trajectoryId)).SingleOrDefault();
            trajectory.IsActive = false;
            int Result = this.context.SaveChanges();
            string Message;
            if (Result > 0)
            {
                Message = "Deleted successfully";
            }
            else
            {
                Message = "Error, please try again!";
            }
            return Json(new { message = Message, id = trajectoryId }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [ValidateInput(false)]
        public ActionResult ListTrajectories()
        {
            var account = this.context.Accounts.Where(x => x.Username.Equals(User.Identity.Name)).SingleOrDefault();
            return RedirectToAction("ListTrajectory", new { SearchKeyword = " ", PageNumber = 1, PageCount = 0, UserId = account.Id, DateFrom = " ", DateTo = " " });
        }

        [ValidateInput(false)]
        [Authorize]
        public ActionResult ListTrajectory(TrajectorySearchCriteriaViewModel searchModel)
        {
            //page size
            int pageSize = 7;

            if (!String.IsNullOrEmpty(searchModel.SearchKeyword))
            {
                searchModel.SearchKeyword = searchModel.SearchKeyword.Trim().ToLower();
            }
            // List trajectory
            var model = new ListTrajectoryViewModel();

            // Get account
            var account = this.context.Accounts.SingleOrDefault(x => x.Id == searchModel.UserId);
            // Get trajectory of the username
            var listTraject = new List<Trajectory>();
            var user = this.context.Accounts.Where(x => x.Username == User.Identity.Name).SingleOrDefault();
            // Condition
            if (!String.IsNullOrEmpty(searchModel.SearchKeyword) && !String.IsNullOrWhiteSpace(searchModel.SearchKeyword))
            {
                string[] trajectName = searchModel.SearchKeyword.Split(new string[] { "" }, StringSplitOptions.RemoveEmptyEntries);
                //listTraject = (from c in this.context.Trajectories where c.TrajectoryName.ToLower().Contains()

                listTraject = account.Trajectories.Where(x => x.TrajectoryName.ToLower().Contains(searchModel.SearchKeyword)
                    && x.IsActive
                    && x.Status.Equals("Public", StringComparison.InvariantCultureIgnoreCase)


                    || x.TrajectoryName.ToLower().Contains(searchModel.SearchKeyword)
                    && x.IsActive
                    && x.UserId == user.Id) //Private
                    .OrderByDescending(x => x.CreatedDate).ToList();
            }
            else
            {
                listTraject = account.Trajectories.Where(x => x.IsActive
                    && x.Status.Equals("Public", StringComparison.InvariantCultureIgnoreCase)

                    || x.IsActive
                    && x.UserId == user.Id)

                    .OrderByDescending(x => x.CreatedDate).ToList();
            }
            searchModel.PageCount = (listTraject.Count - 1) / pageSize + 1;
            listTraject = listTraject.Skip((searchModel.PageNumber - 1) * pageSize).Take(pageSize).ToList();


            foreach (var trajectory in listTraject)
            {
                var trajectoryViewModel = new TrajectoryViewModel();
                trajectoryViewModel.Id = trajectory.Id;
                trajectoryViewModel.TrajectoryName = trajectory.TrajectoryName;
                trajectoryViewModel.Description = trajectory.Description;
                trajectoryViewModel.Status = trajectory.Status;
                trajectoryViewModel.CreateDate = trajectory.CreatedDate.ToString("dd/MM/yyyy HH:mm:ss tt");
                trajectoryViewModel.LastUpdate = trajectory.LastUpdated.ToString("dd/MM/yyyy HH:mm:ss tt");
                var listLocation = trajectory.Locations.Where(x => x.IsActive).OrderBy(x => x.CreatedDate).ToList();
                var startLocation = listLocation.FirstOrDefault();
                var endLocation = listLocation.LastOrDefault();
                if (listLocation.Count > 0)
                {
                    trajectoryViewModel.StartLongitude = startLocation.Longitude;
                    trajectoryViewModel.StartLatitude = startLocation.Latitude;
                    trajectoryViewModel.EndLatitude = endLocation.Latitude;
                    trajectoryViewModel.EndLongitude = endLocation.Longitude;
                    trajectoryViewModel.CenterLatitude = listLocation.Average(x => x.Latitude);
                    trajectoryViewModel.CenterLongitude = listLocation.Average(x => x.Longitude);
                    trajectoryViewModel.StartAddress = startLocation.Address;
                    trajectoryViewModel.EndAddress = endLocation.Address;
                    trajectoryViewModel.StartTime = startLocation.CreatedDate.ToString("dd/MM/yyyy HH:mm:ss tt");
                    trajectoryViewModel.EndTime = endLocation.CreatedDate.ToString("dd/MM/yyyy HH:mm:ss tt");
                    trajectoryViewModel.TotalLocation = listLocation.Count;
                }
                else
                {
                    trajectoryViewModel.TotalLocation = 0;
                }
                model.ListTrajectory.Add(trajectoryViewModel);
            }

            ViewBag.SearchCriteriaViewModel = searchModel;

            // Get User
            var userModel = GetUserViewModel(account);
            model.FriendViewModel = userModel;
            ViewBag.FriendStatus = userModel.FriendStatus;
            return View(model);
        }

        private FriendViewModel GetUserViewModel(Account account)
        {
            var myAccount = this.context.Accounts.SingleOrDefault(a => a.Username.Equals(User.Identity.Name, StringComparison.InvariantCultureIgnoreCase));
            var userModel = new FriendViewModel();
            if (String.IsNullOrEmpty(account.Avatar))
            {
                userModel.Avatar = "/DefaultUserData/Avatar/Avatar.png";
            }
            else
            {
                userModel.Avatar = account.Avatar;
            }
            userModel.Email = account.Email;
            userModel.Fullname = account.Fullname;
            userModel.IsActive = account.IsActive.ToString();
            userModel.LastLogin = account.LastLogin;
            userModel.Username = account.Username;
            userModel.Id = account.Id;
            userModel.Address = account.Address;
            userModel.Birthday = account.Birthday;
            userModel.Gender = account.Gender;
            // if user is not current user
            if (account.Id != myAccount.Id)
            {
                //check friend condition
                if (account.FriendShips1.Where(x => x.Account.Id == myAccount.Id).Any() && account.FriendShips1.Where(x => x.Account.Id == myAccount.Id).SingleOrDefault().Status == FriendStatus.IS_FRIEND
                        && myAccount.FriendShips1.Where(x => x.Account.Id == account.Id).Any() && myAccount.FriendShips1.Where(x => x.Account.Id == account.Id).SingleOrDefault().Status == FriendStatus.IS_FRIEND)
                {
                    userModel.FriendStatus = FriendStatus.IS_FRIEND;
                }
                else
                {
                    userModel.FriendStatus = FriendStatus.NOT_FRIEND;
                }
            }

            return userModel;
        }

        public async Task<JsonResult> GetLocationList(string trajectId)
        {

MobileSurveillanceWebApplication/Views/Report/Report.cshtml
@model MobileSurveillanceWebApplication.Models.ViewModel.TrajectoryViewModel

@{
    ViewBag.Title = "Report";
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
    <title>Mobile Surveillance - Report</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")

</head>
<body id="login-body">
    <div class="container" id="container">
        <!-- Main -->
        <div class="row">
            @{
                Html.RenderPartial("~/Views/Report/ReportPartialMobile.cshtml", Model);
            }
        </div>
        <!-- End of main -->
        <!-- Footer -->
        <div class="row" id="footer">
        </div>
        <!-- End of Footer -->
    </div>
    <!-- Javasript here -->
</body>
</html>

MobileSurveillanceWebApplication/Views/Report/ReportPartial.cshtml
@model MobileSurveillanceWebApplication.Models.ViewModel.TrajectoryViewModel
<script src="@Url.Content("~/Scripts/amcharts/amcharts.js")"></script>
<script src="@Url.Content("~/Scripts/amcharts/serial.js")"></script>
<!-- scripts for exporting chart as an image -->
<!-- Exporting to image works on all modern browsers except IE9 (IE10 works fine) -->
<!-- Note, the exporting will work only if you view the file from web server -->
<!--[if (!IE) | (gte IE 10)]> -->
<script src="@Url.Content("~/Scripts/amcharts/exporting/amexport.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/amcharts/exporting/canvg.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/amcharts/exporting/filesaver.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/amcharts/exporting/jspdf.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/amcharts/exporting/jspdf.plugin.addimage.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/amcharts/exporting/rgbcolor.js")" type="text/javascript"></script>

<!-- <![endif]-->
<script type="text/javascript">
    $(document).ready(function () {
        var chart;
        var graph;
        $("#summary-report").hide();
        $.getJSON("/Report/GetReportData/", { trajectoryId: '@Model.Id' }, function (responseData) {
            var chartData = responseData.ChartData;
            $("#total-distance").text("Total Distances: " + chartData[chartData.length - 1].TotalDistance + " Kilometers");
            $("#total-location").text("Total Locations: " + "@Model.TotalLocation");
            $("#total-time").text("Total Time: " + "@Model.TotalTime");
            // SERIAL CHART
            chart = new AmCharts.AmSerialChart();
            chart.pathToImages = "@Url.Content("~/Scripts/amcharts/images/")";
            chart.dataProvider = chartData;
            chart.marginLeft = 10;
            chart.categoryField = "TakenDate";
            chart.allLabels = [
                { "x": 50, "y": 50, "text": responseData.TrajectoryName, "align": "center", "size": 24, "color": "#0066CC", "alpha": 1, "rotation": 0, "bold": true, "url": "@Url.Action("ViewDetail", "Trajectory", new { trajectoryId = Model.Id})" },
                { "x": 50, "y": 80, "text": "@Model.CreateDate", "align": "center", "size": 16, "color": "#0066CC", "alpha": 1, "rotation": 0, "bold": true, "url": "@Url.Action("ViewDetail", "Trajectory", new { trajectoryId = Model.Id})" }
            ];

            // AXES
            // category
            var categoryAxis = chart.categoryAxis;
            categoryAxis.dashLength = 3;
            categoryAxis.minorGridEnabled = true;
            categoryAxis.minorGridAlpha = 0.1;
            categoryAxis.autoWrap = true;
            categoryAxis.offset = 20;
            categoryAxis.title = "Time Line";

            // value
            var valueAxis = new AmCharts.ValueAxis();
            valueAxis.axisAlpha = 0;
            valueAxis.inside = true;
            valueAxis.dashLength = 10;
            valueAxis.title = "Distance";
            chart.addValueAxis(valueAxis);

            // GRAPH 2
            graph1 = new AmCharts.AmGraph();
            graph1.type = "smoothedLine"; // this line makes the graph smoothed line.
            graph1.lineColor = "#d1655d";
            //graph.bullet = "round";
            graph1.bulletSize = 32;
            graph1.bulletOffset = 20;
            graph1.bulletBorderColor = "#FFFFFF";
            graph1.bulletBorderAlpha = 1;
            graph1.bulletBorderThickness = 2;
            graph1.lineThickness = 3;
            graph1.valueField = "Distance";
            graph1.customBulletField = "Marker";
            graph1.balloonText = "<span style='color:red; font-size:10px'>[[category]]</span>" +
                "<br><b><span style='font-size:13px;'>Location: [[LocationNumber]]</span></b>" +
                "<br><b><span style='font-size:13px;'>Velocity: [[Velocity]] Km/h</span></b>" +
                "<br><b><span style='font-size:13px;'>Distance: [[value]] Km</span></b>" +
                "<br><b><span style='font-size:13px;'>Time Interval: [[TimeInterval]]</span></b>" +
                "<br><b><span style='font-size:13px;'>GPS: ([[Latitude]], [[Longitude]])</span></b>" +
                "<br><b><span style='font-size:13px;'>Address: [[Address]]</span></b>";
            chart.addGraph(graph1);


            // GRAPH 2
            graph2 = new AmCharts.AmGraph();
            graph2.type = "smoothedLine"; // this line makes the graph smoothed line.
            graph2.lineColor = "#3333FF";
            //graph.bullet = "round";
            graph2.bulletSize = 32;
            graph2.bulletOffset = 20;
            graph2.bulletBorderColor = "#FFFFFF";
            graph2.bulletBorderAlpha = 1;
            graph2.bulletBorderThickness = 2;
            graph2.lineThickness = 4;
            graph2.valueField = "TotalDistance";
            graph2.customBulletField = "Marker";
            graph2.balloonText = null;
            graph2.balloonText = "<span style='color:red; font-size:10px'>[[category]]</span>" +
                "<br><b><span style='font-size:13px;'>Location: [[LocationNumber]]</span></b>" +
                "<br><b><span style='font-size:13px;'>Total Time: [[TotalTime]]</span></b>" +
                "<br><b><span style='font-size:13px;'>Total Distance: [[TotalDistance]] Km</span></b>";
            chart.addGraph(graph2);

            // CURSOR
            var chartCursor = new AmCharts.ChartCursor();
            chartCursor.cursorAlpha = 0;
            chartCursor.cursorPosition = "mouse";
            chart.addChartCursor(chartCursor);

            // SCROLLBAR
            var chartScrollbar = new AmCharts.ChartScrollbar();
            chart.addChartScrollbar(chartScrollbar);

            chart.creditsPosition = "bottom-right";

            chart.exportConfig = {
                menuTop: "80px",
                menuBottom: "auto",
                menuRight: "20px",
                backgroundColor: "#efefef",

                menuItemStyle	: {
                    backgroundColor			: '#EFEFEF',
                    rollOverBackgroundColor	: '#DDDDDD'},

                menuItems: [{
                    textAlign: 'center',
                    icon: '@Url.Content("~/Scripts/amcharts/images/export.png")',
                    onclick:function(){},
                    iconTitle: 'Save chart as an image',
                    items: [{
                        title: 'JPG',
                        format: 'jpg'
                    }, {
                        title: 'PNG',
                        format: 'png'
                    }, {
                        title: 'SVG',
                        format: 'svg'
                    }, {
                        title: 'PDF',
                        format: 'pdf'
                    }]
                }]
            };

            // WRITE
            chart.write("chartdiv");
            $("#summary-report").show();
        });
    });
</script>
<div class="col-lg-6 col-md-6 col-sm-12">
    <div id="summary-report" class="alert alert-info summary-report">
        <div id="total-location">
        </div>
        <div id="total-distance">
        </div>
        <div id="total-time">
        </div>
    </div>
</div>
<div class="col-lg-6 col-md-6 col-sm-12">
    @using (Html.BeginForm("ExcelReport", "Report", FormMethod.Post, new { enctype = "multipart/form-data", id="report-download-form" }))
    {
        <input type="hidden" name="trajectoryId" value="@Model.Id" />
        <input class="download-report" type="submit" name="Export" id="Export" value="" />
    }
</div>
<div id="chartdiv" style="width: 90%; height: 550px; margin-left: 18px; margin-right: auto;"></div>

MobileSurveillanceWebApplication/Views/Report/ReportPartialMobile.cshtml
@model MobileSurveillanceWebApplication.Models.ViewModel.TrajectoryViewModel
<script src="@Url.Content("~/Scripts/amcharts/amcharts.js")"></script>
<script src="@Url.Content("~/Scripts/amcharts/serial.js")"></script>
<!-- scripts for exporting chart as an image -->
<!-- Exporting to image works on all modern browsers except IE9 (IE10 works fine) -->
<!-- Note, the exporting will work only if you view the file from web server -->
<!--[if (!IE) | (gte IE 10)]> -->
<script src="@Url.Content("~/Scripts/amcharts/exporting/amexport.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/amcharts/exporting/canvg.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/amcharts/exporting/filesaver.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/amcharts/exporting/jspdf.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/amcharts/exporting/jspdf.plugin.addimage.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/amcharts/exporting/rgbcolor.js")" type="text/javascript"></script>

<!-- <![endif]-->
<script type="text/javascript">
    var chart;
    var graph;
    $(document).ready(function () {
        $("#summary-report").hide();
        $.getJSON("/Report/GetReportDataForMobile/", { trajectoryId: '@Model.Id' }, function (responseData) {
            var chartData = responseData.ChartData;

            $("#report-trajectory-name").text("Trajectory: " + responseData.TrajectoryName);
            $("#report-trajectory-author").text("Author: " + responseData.Author);
            $("#total-distance").text("Total Distances: " + chartData[chartData.length - 1].TotalDistance + " Kilometers");
            $("#total-location").text("Total Locations: " + "@Model.TotalLocation");
            $("#total-time").text("Total Time: " + "@Model.TotalTime");
            // SERIAL CHART
            chart = new AmCharts.AmSerialChart();
            chart.pathToImages = "@Url.Content("~/Scripts/amcharts/images/")";
            chart.dataProvider = chartData;
            chart.marginLeft = 10;
            chart.categoryField = "TakenDate";
            chart.allLabels = [
                { "x": 50, "y": 50, "text": responseData.TrajectoryName, "align": "center", "size": 24, "color": "#0066CC", "alpha": 1, "rotation": 0, "bold": true, "url": "@Url.Action("ViewDetail", "Trajectory", new { trajectoryId = Model.Id})" },
                { "x": 50, "y": 80, "text": "@Model.CreateDate", "align": "center", "size": 16, "color": "#0066CC", "alpha": 1, "rotation": 0, "bold": true, "url": "@Url.Action("ViewDetail", "Trajectory", new { trajectoryId = Model.Id})" }
            ];

            // AXES
            // category
            var categoryAxis = chart.categoryAxis;
            categoryAxis.dashLength = 3;
            categoryAxis.minorGridEnabled = true;
            categoryAxis.minorGridAlpha = 0.1;
            categoryAxis.autoWrap = true;
            categoryAxis.offset = 20;
            categoryAxis.title = "Time Line";

            // value
            var valueAxis = new AmCharts.ValueAxis();
            valueAxis.axisAlpha = 0;
            valueAxis.inside = true;
            valueAxis.dashLength = 10;
            valueAxis.title = "Distance";
            chart.addValueAxis(valueAxis);

            // GRAPH 2
            graph1 = new AmCharts.AmGraph();
            graph1.type = "smoothedLine"; // this line makes the graph smoothed line.
            graph1.lineColor = "#d1655d";
            //graph.bullet = "round";
            graph1.bulletSize = 32;
            graph1.bulletOffset = 20;
            graph1.bulletBorderColor = "#FFFFFF";
            graph1.bulletBorderAlpha = 1;
            graph1.bulletBorderThickness = 2;
            graph1.lineThickness = 3;
            graph1.valueField = "Distance";
            graph1.customBulletField = "Marker";
            graph1.balloonText = "<span style='color:red; font-size:10px'>[[category]]</span>" +
                "<br><b><span style='font-size:13px;'>Location: [[LocationNumber]]</span></b>" +
                "<br><b><span style='font-size:13px;'>Velocity: [[Velocity]] Km/h</span></b>" +
                "<br><b><span style='font-size:13px;'>Distance: [[value]] Km</span></b>" +
                "<br><b><span style='font-size:13px;'>Time Interval: [[TimeInterval]]</span></b>" +
                "<br><b><span style='font-size:13px;'>GPS: ([[Latitude]], [[Longitude]])</span></b>" +
                "<br><b><span style='font-size:13px;'>Address: [[Address]]</span></b>";
            chart.addGraph(graph1);


            // GRAPH 2
            graph2 = new AmCharts.AmGraph();
            graph2.type = "smoothedLine"; // this line makes the graph smoothed line.
            graph2.lineColor = "#3333FF";
            //graph.bullet = "round";
            graph2.bulletSize = 32;
            graph2.bulletOffset = 20;
            graph2.bulletBorderColor = "#FFFFFF";
            graph2.bulletBorderAlpha = 1;
            graph2.bulletBorderThickness = 2;
            graph2.lineThickness = 4;
            graph2.valueField = "TotalDistance";
            graph2.customBulletField = "Marker";
            graph2.balloonText = null;
            graph2.balloonText = "<span style='color:red; font-size:10px'>[[category]]</span>" +
                "<br><b><span style='font-size:13px;'>Location: [[LocationNumber]]</span></b>" +
                "<br><b><span style='font-size:13px;'>Total Time: [[TotalTime]]</span></b>" +
                "<br><b><span style='font-size:13px;'>Total Distance: [[TotalDistance]] Km</span></b>";
            chart.addGraph(graph2);

            // CURSOR
            var chartCursor = new AmCharts.ChartCursor();
            chartCursor.cursorAlpha = 0;
            chartCursor.cursorPosition = "mouse";
            chart.addChartCursor(chartCursor);

            // SCROLLBAR
            var chartScrollbar = new AmCharts.ChartScrollbar();
            chart.addChartScrollbar(chartScrollbar);

            chart.creditsPosition = "bottom-right";

            chart.exportConfig = {
                menuTop: "80px",
                menuBottom: "auto",
                menuRight: "20px",
                backgroundColor: "#efefef",

                menuItemStyle: {
                    backgroundColor: '#EFEFEF',
                    rollOverBackgroundColor: '#DDDDDD'
                },

                menuItems: [{
                    textAlign: 'center',
                    icon: '@Url.Content("~/Scripts/amcharts/images/export.png")',
                    onclick: function () { },
                    iconTitle: 'Save chart as an image',
                    items: [{
                        title: 'JPG',
                        format: 'jpg'
                    }, {
                        title: 'PNG',
                        format: 'png'
                    }, {
                        title: 'SVG',
                        format: 'svg'
                    }, {
                        title: 'PDF',
                        format: 'pdf'
                    }]
                }]
            };

            // WRITE
            chart.write("chartdiv");
            $("#summary-report").show();
        });
    });
</script>
<div class="col-lg-6 col-md-6 col-sm-12">
    <div id="summary-report" class="alert alert-warning summary-report">
        <div id="report-trajectory-name">
        </div>
        <div id="report-trajectory-author">
        </div>
        <div id="total-location">
        </div>
        <div id="total-distance">
        </div>
        <div id="total-time">
        </div>
    </div>
</div>
<div id="chartdiv" style="width: 90%; height: 550px; margin-left: 18px; margin-right: auto;"></div>