MobileSurveillanceWebApplication/Controllers/UserController.cs
using MobileSurveillanceWebApplication.Models.DatabaseModel;
using MobileSurveillanceWebApplication.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace MobileSurveillanceWebApplication.Controllers
{
    public class UserController : Controller
    {
        private const string IS_FRIEND = "1";
        private const string NOT_FRIEND = "0";
        //
        // GET: /User/
        private readonly MobileSurveillanceContext context = new MobileSurveillanceContext();

        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// ListFriend redirect to ListUser
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult ListFriend()
        {
            return RedirectToAction("ListUser", new { SearchKeyword = "", PageNumber = 1, PageCount = 0 });
        }

        [HttpGet]
        [Authorize]
        [ValidateInput(false)]
        public JsonResult GetListFriend(string query)
        {
            query = HttpUtility.UrlDecode(query);
            // Get user account
            var accountId = this.context.Accounts.Where(x => x.Username.Equals(User.Identity.Name, StringComparison.InvariantCultureIgnoreCase)).SingleOrDefault().Id;
            ICollection<FriendShip> listFriendShip = null;
            if (String.IsNullOrEmpty(query))
            {
                listFriendShip = this.context.FriendShips
                    .Where(x => x.MyId == accountId)
                    .Where(x => x.Status.Equals(IS_FRIEND, StringComparison.InvariantCultureIgnoreCase))
                    .OrderBy(x => x.Account.Username)
                    .OrderBy(x => x.Account.Fullname)
                    .ToList();
            }
            else
            {
                listFriendShip = this.context.FriendShips
                    .Where(x => x.MyId == accountId)
                    .Where(x => x.Status.Equals(IS_FRIEND, StringComparison.InvariantCultureIgnoreCase))
                    .Where(x => x.Account.Fullname.ToLower().Contains(query.ToLower()) || x.Account.Username.ToLower().Contains(query.ToLower()) || x.Account.Email.ToLower().Contains(query.ToLower()))
                    .OrderBy(x => x.Account.Username)
                    .OrderBy(x => x.Account.Fullname)
                    .ToList();
            }
            var listResult = new List<string>();
            for (int i = 0; i < listFriendShip.Count; i++)
            {
                var myId = listFriendShip.ElementAt(i).MyId;
                var myFriendId = listFriendShip.ElementAt(i).MyFriendId;
                var isBothFriend = this.context.FriendShips
                    .Where(x => x.MyId == myFriendId)
                    .Where(x => x.MyFriendId == myId)
                    .Where(x => x.Status.Equals(IS_FRIEND, StringComparison.InvariantCultureIgnoreCase))
                    .Any();
                if (isBothFriend)
                {
                    listResult.Add(listFriendShip.ElementAt(i).Account.Fullname);
                    listResult.Add(listFriendShip.ElementAt(i).Account.Username);
                    listResult.Add(listFriendShip.ElementAt(i).Account.Email);
                }
            }
            return Json(listResult, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// List All Friends
        /// </summary>
        /// <returns></returns>
        [ValidateInput(false)]
        [Authorize]
        public ActionResult ListUser(SearchCriteriaViewModel searchUserModel)
        {
            int pageSize = 12;
            var listUserModel = new ListUserViewModel();
            // get User
            var account = this.context.Accounts.SingleOrDefault(a => a.Username.Equals(User.Identity.Name, StringComparison.InvariantCultureIgnoreCase));

            var listFriendShip = new List<FriendShip>();
            var listMyFriend = new List<FriendShip>();
            // Condition
            if (!String.IsNullOrEmpty(searchUserModel.SearchKeyword) && !String.IsNullOrWhiteSpace(searchUserModel.SearchKeyword))
            {
                searchUserModel.SearchKeyword = searchUserModel.SearchKeyword.Trim().ToLower();
                listFriendShip = account.FriendShips1.Where(x => x.Account.Fullname.ToLower().Contains(searchUserModel.SearchKeyword)
                   || x.Account.Username.ToLower().Contains(searchUserModel.SearchKeyword) && x.Status == IS_FRIEND).ToList();
            }
            else
            {
                listFriendShip = account.FriendShips1.Where(x => x.Status == IS_FRIEND).ToList();
            }


            //Add who is friend to ListFriend
            foreach (var friendship in listFriendShip)
            {
                if (account.FriendShips1.Where(x => x.Account.Id == friendship.Account.Id).Any() && account.FriendShips1.Where(x => x.Account.Id == friendship.Account.Id).SingleOrDefault().Status == IS_FRIEND
                    && friendship.Account.FriendShips1.Where(x => x.Account.Id == account.Id).Any() && friendship.Account.FriendShips1.Where(x => x.Account.Id == account.Id).SingleOrDefault().Status == IS_FRIEND)
                {
                    listMyFriend.Add(friendship);
                }
            }
            // For Pagination
            searchUserModel.PageCount = (listMyFriend.Count - 1) / pageSize + 1;
            listMyFriend = listMyFriend.Skip((searchUserModel.PageNumber - 1) * pageSize).Take(pageSize).ToList();

            //List all friends
            foreach (var user in listMyFriend)
            {
                var userViewModel = new UserViewModel();
                userViewModel.Id = user.Account.Id;
                userViewModel.Username = user.Account.Username;
                userViewModel.Avatar = user.Account.Avatar;
                userViewModel.Fullname = user.Account.Fullname;
                userViewModel.Address = user.Account.Address;
                userViewModel.Birthday = user.Account.Birthday;
                userViewModel.ModelListUserId = String.Format("model-listUser-{0}-{1}", account.Id, user.Account.Id);
                listUserModel.ListUser.Add(userViewModel);
            }
            listUserModel.ListUser = listUserModel.ListUser.OrderBy(x => x.Fullname).ToList();

            //add searchUserModel to ViewBag
            ViewBag.SearchCriteriaViewModel = searchUserModel;
            listUserModel.ListNotFriend = LoadSuggestFriend();
            return View(listUserModel);
        }

        /// <summary>
        /// Track User Function
        /// </summary>
        /// <param name="friendID"></param>
        /// <returns></returns>
        [Authorize]
        public ActionResult ListFriendTrajectory(long friendId)
        {
            return RedirectToAction("ListTrajectory", "Trajectory", new { SearchKeyword = " ", PageNumber = 1, PageCount = 0, UserId = friendId, DateFrom = " ", DateTo = " " });
        }

        /// <summary>
        /// Get count for Inbox and for FriendList
        /// </summary>
        /// <returns></returns>
        public JsonResult GetCountItems()
        {
            string username = User.Identity.Name;
            var account = this.context.Accounts.SingleOrDefault(a => a.Username.Equals(username, StringComparison.InvariantCultureIgnoreCase));
            var listUser = this.context.Accounts.ToList();
            listUser.Remove(account);
            var listFriend = new List<Account>();
            var listInbox = new List<Account>();

            foreach (var user in listUser)
            {
                //Add who is friend to ListFriend
                if (account.FriendShips1.Where(x => x.Account.Id == user.Id).Any() && account.FriendShips1.Where(x => x.Account.Id == user.Id).SingleOrDefault().Status == IS_FRIEND
                    && user.FriendShips1.Where(x => x.Account.Id == account.Id).Any() && user.FriendShips1.Where(x => x.Account.Id == account.Id).SingleOrDefault().Status == IS_FRIEND)
                {
                    listFriend.Add(user);
                }
                //Add who is waiting for confirmation to ListInbox
                else if (user.FriendShips1.Where(x => x.Account.Id == account.Id).Any() && user.FriendShips1.Where(x => x.Account.Id == account.Id).SingleOrDefault().Status == IS_FRIEND
                    && (!account.FriendShips1.Where(x => x.Account.Id == user.Id).Any() || account.FriendShips1.Where(x => x.Account.Id == user.Id).SingleOrDefault().Status == NOT_FRIEND))
                {
                    listInbox.Add(user);
                }
            }

            var countItem = new
            {
                countInbox = listInbox.Count(),
                countFriends = listFriend.Count(),
            };
            return Json(countItem, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Make Friend Request
        /// </summary>
        /// <param name="friendId"></param>
        /// <returns></returns>
        [Authorize]
        public ActionResult MakeFriendRequest(long friendId)
        {
            return RedirectToAction("ListTrajectory", "Trajectory", new { SearchKeyword = " ", PageNumber = 1, PageCount = 0, UserId = friendId, DateFrom = " ", DateTo = " " });
        }

        /// <summary>
        /// List all Inbox for confirm Request
        /// </summary>
        [Authorize]
        public ActionResult ListInbox(SearchCriteriaViewModel searchUserModel)
        {
            var listUserModel = new ListUserViewModel();
            // get User
            var account = this.context.Accounts.SingleOrDefault(a => a.Username == User.Identity.Name);
            var listInbox = new List<FriendShip>();
            var listFriendShip = account.FriendShips.Where(x => x.Status == IS_FRIEND).ToList();

            //Add who is waiting confirm to ListInbox
            foreach (var friendship in listFriendShip)

MobileSurveillanceWebApplication/Views/SearchResult/SearchResult.cshtml
@model MobileSurveillanceWebApplication.Models.ViewModel.ListFriendViewModel
@{
    ViewBag.Title = "SearchResult";
    var searchUserModel = (MobileSurveillanceWebApplication.Models.ViewModel.SearchCriteriaViewModel)ViewBag.SearchCriteriaViewModel;
}

<script>
    function onSuccess(response, status, data) {
        window.location = "?SearchKeyword=" + response.SearchKeyword + "&PageNumber=" + response.PageNumber + "&PageCount=" + response.PageCount;
    }

    function onFailure() {
        alert('Something went wrong, please try again!');
    }
</script>

<div class="row" style="margin-left: 0px">
    @if (ViewBag.SearchUserCount > 0)
    {
        <div class="alert alert-info" style="margin-top: 25px; margin-left: 18px; width: 600px"><h4><b>Search returns @ViewBag.SearchUserCount people of "@searchUserModel.SearchKeyword"</b></h4></div>
    }
    else
    {
        <div class="alert alert-info" style="margin-top: 25px; margin-left: 18px; width: 600px"><h4><b>There is no people "@searchUserModel.SearchKeyword" in the system</b></h4></div>
    }
</div>
<div class="row" style="margin-left: 0px">
    @foreach (var item in Model.ListFriend)
    {
    <!-- Listing User-->
        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-6">
            <div class="list-thumb">
                <div class="row" align="center">
                    <img src="@item.Avatar" alt="Mobile Surveillance" class="avatar-thumbnail">
                </div>
                <div class="row" align="center">
                    <h4>@Html.ActionLink(item.Fullname, "ListFriendTrajectory", "User", new { friendId = @item.Id }, htmlAttributes: new { @class = "" })</h4>
                </div>
                <div class="row" align="center">
                    <h4 id="@item.ModelSearchId">
                        @if (item.MyId == item.Id)
                        {
                            @Html.ActionLink("Track User", "ListFriendTrajectory", "User", new { friendId = @item.Id }, htmlAttributes: new { @class = "label label-success" })
                        }
                        else
                        {
                            if (item.FriendStatus.Equals(MobileSurveillanceWebApplication.Models.ViewModel.FriendStatus.NOT_FRIEND, StringComparison.InvariantCultureIgnoreCase))
                            {
                                @Ajax.ActionLink("Add Friend", "AddFriend", new { friendId = item.Id, requestType = "addFriend", SearchKeyword = searchUserModel.SearchKeyword, PageNumber = searchUserModel.PageNumber, PageCount = searchUserModel.PageCount }, new AjaxOptions()
                                    {
                                        HttpMethod = "POST",
                                        OnSuccess = "onSuccess",
                                        OnFailure = "",
                                    }, new { @class = "label label-primary" })
                            }
                            else if (item.FriendStatus.Equals(MobileSurveillanceWebApplication.Models.ViewModel.FriendStatus.REQUEST_SENT, StringComparison.InvariantCultureIgnoreCase))
                            {
                                @Ajax.ActionLink("Cancel Request", "CancelRequest", new { friendId = item.Id, SearchKeyword = searchUserModel.SearchKeyword, PageNumber = searchUserModel.PageNumber, PageCount = searchUserModel.PageCount }, new AjaxOptions()
                                    {
                                        HttpMethod = "POST",
                                        OnSuccess = "onSuccess",
                                        OnFailure = "",
                                    }, new { @class = "label label-danger" })
                            }
                            else if (item.FriendStatus.Equals(MobileSurveillanceWebApplication.Models.ViewModel.FriendStatus.CONFIRM_NEED, StringComparison.InvariantCultureIgnoreCase))
                            {
                                @Ajax.ActionLink("Accept Request", "AddFriend", new { friendId = item.Id, requestType = "confirmRequest", SearchKeyword = searchUserModel.SearchKeyword, PageNumber = searchUserModel.PageNumber, PageCount = searchUserModel.PageCount }, new AjaxOptions()
                                   {
                                       HttpMethod = "POST",
                                       OnSuccess = "onSuccess",
                                       OnFailure = "",
                                   }, new { @class = "label label-primary" })

                                @Ajax.ActionLink("Deny Request", "DenyRequest", "SearchResult", new { friendId = @item.Id, requestType = "denyRequest", SearchKeyword = searchUserModel.SearchKeyword, PageNumber = searchUserModel.PageNumber, PageCount = searchUserModel.PageCount }, new AjaxOptions()
                                   {
                                       HttpMethod = "POST",
                                       OnSuccess = "onSuccess",
                                       OnFailure = "",
                                   }, new { @class = "label label-warning" })
                            }
                            else if (item.FriendStatus.Equals(MobileSurveillanceWebApplication.Models.ViewModel.FriendStatus.NOT_YET_FRIEND, StringComparison.InvariantCultureIgnoreCase))
                            {
                                @Ajax.ActionLink("Add Friend", "AddFriend", new { friendId = item.Id, requestType = "addFriend", SearchKeyword = searchUserModel.SearchKeyword, PageNumber = searchUserModel.PageNumber, PageCount = searchUserModel.PageCount }, new AjaxOptions()
                                    {
                                        HttpMethod = "POST",
                                        OnSuccess = "onSuccess",
                                        OnFailure = "",
                                    }, new { @class = "label label-primary" })
                            }
                            else
                            {
                                @Html.ActionLink("Track User", "ListFriendTrajectory", "User", new { friendId = @item.Id }, htmlAttributes: new { @class = "label label-success" })
                            }
                        }
                    </h4>
                </div>
            </div>
        </div>
    }
</div>
<!-- Paging-->
<div class="row" style="text-align: center;clear:both">
    <div style="text-align: left; display: inline-block; /* for ie6/7: */ *display: inline; zoom: 1;">
        <ul class="pagination">

            <li>@Html.ActionLink("First", "SearchResult", new { SearchKeyword = searchUserModel.SearchKeyword, PageNumber = 1, PageCount = searchUserModel.PageCount })</li>
            @if (searchUserModel.PageNumber > 1)
            {
                <li>@Html.ActionLink("<<", "SearchResult", new { SearchKeyword = searchUserModel.SearchKeyword, PageNumber = searchUserModel.PageNumber - 1, PageCount = searchUserModel.PageCount })</li>
            }
            @if (searchUserModel.PageCount > 5)
            {
                int firstSegmentLength = 3;
                while (searchUserModel.PageNumber - firstSegmentLength < 0)
                {
                    firstSegmentLength--;
                }

                int lastSegment = searchUserModel.PageNumber + 3;


                if (lastSegment > searchUserModel.PageCount)
                {
                    lastSegment = searchUserModel.PageCount;
                }

                for (int i = searchUserModel.PageNumber - firstSegmentLength + 1; i < searchUserModel.PageNumber; i++)
                {
                    <li>@Html.ActionLink((i).ToString(), "SearchResult", new { SearchKeyword = searchUserModel.SearchKeyword, PageNumber = i, PageCount = searchUserModel.PageCount })</li>
                }
                <li class="active">@Html.ActionLink((searchUserModel.PageNumber).ToString(), "SearchResult", new { SearchKeyword = searchUserModel.SearchKeyword, PageNumber = searchUserModel.PageNumber, PageCount = searchUserModel.PageCount })</li>
                for (int i = searchUserModel.PageNumber + 1; i <= lastSegment + 3 - firstSegmentLength; i++)
                {
                    <li>@Html.ActionLink((i).ToString(), "SearchResult", new { SearchKeyword = searchUserModel.SearchKeyword, PageNumber = i, PageCount = searchUserModel.PageCount })</li>
                }
            }
            else
            {
                for (int i = 1; i <= searchUserModel.PageCount; i++)
                {
                    if (i == searchUserModel.PageNumber)
                    {
                        <li class="active">@Html.ActionLink((i).ToString(), "SearchResult", new { SearchKeyword = searchUserModel.SearchKeyword, PageNumber = searchUserModel.PageNumber, PageCount = searchUserModel.PageCount })</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink((i).ToString(), "SearchResult", new { SearchKeyword = searchUserModel.SearchKeyword, PageNumber = i, PageCount = searchUserModel.PageCount })</li>
                    }
                }
            }
            @if (searchUserModel.PageNumber < searchUserModel.PageCount)
            {
                <li>@Html.ActionLink(">>", "SearchResult", new { SearchKeyword = searchUserModel.SearchKeyword, PageNumber = searchUserModel.PageNumber + 1, PageCount = searchUserModel.PageCount })</li>
            }
            <li>@Html.ActionLink("Last", "SearchResult", new { SearchKeyword = searchUserModel.SearchKeyword, PageNumber = searchUserModel.PageCount, PageCount = searchUserModel.PageCount })</li>
        </ul>
    </div>
</div>
<!-- Paging-->